
  const recomandedProducts = [
    {
      title: 'C-500 Antioxidant Protect Dietary Supplement',
      store: 'Lucky Supermarket',
      image: 'assets/images/thumbs/product-img7.png',
      price: '$14.99',
      originalPrice: '$28.99',
      rating: 4.8,
      badge: null,
      badgeClass: '',
      reviewCount: 17,
    },
    {
      title: "Marcel's Modern Pantry Almond Unsweetened",
      store: 'Lucky Supermarket',
      image: 'assets/images/thumbs/product-img8.png',
      price: '$14.99',
      originalPrice: '$28.99',
      rating: 4.8,
      badge: 'Sale 50%',
      badgeClass: 'bg-danger-600 px-8 py-4 text-sm text-white',
      reviewCount: 17,
    },
    {
      title: 'O Organics Milk, Whole, Vitamin D',
      store: 'Lucky Supermarket',
      image: 'assets/images/thumbs/product-img9.png',
      price: '$14.99',
      originalPrice: '$28.99',
      unit: '/Qty',
      rating: 4.8,
      reviewCount: 17,
      badge: 'Sale 50%',
      badgeClass: 'bg-danger-600 px-8 py-4 text-sm text-white',
    },
    {
      title: 'Whole Grains and Seeds Organic Bread',
      store: 'Lucky Supermarket',
      image: 'assets/images/thumbs/product-img10.png',
      price: '$14.99',
      originalPrice: '$28.99',
      unit: '/Qty',
      rating: 4.8,
      reviewCount: 17,
      badge: 'Best Sale',
      badgeClass: 'bg-info-600 px-8 py-4 text-sm text-white',
    },
    {
      title: 'Lucerne Yogurt, Lowfat, Strawberry',
      store: 'Lucky Supermarket',
      image: 'assets/images/thumbs/product-img11.png',
      price: '$14.99',
      originalPrice: '$28.99',
      unit: '/Qty',
      rating: 4.8,
      reviewCount: 17,
      badge: '',
      badgeClass: '',
    },
    {
      title: 'Nature Valley Whole Grain Oats and Honey Protein',
      store: 'Lucky Supermarket',
      image: 'assets/images/thumbs/product-img12.png',
      price: '$14.99',
      originalPrice: '$28.99',
      unit: '/Qty',
      rating: 4.8,
      reviewCount: 17,
      badge: 'Sale 50%',
      badgeClass: 'bg-danger-600',
    },
    {
      title: 'C-500 Antioxidant Protect Dietary Supplement',
      store: 'Lucky Supermarket',
      image: 'assets/images/thumbs/product-img13.png',
      price: '$14.99',
      originalPrice: '$28.99',
      unit: '/Qty',
      rating: 4.8,
      reviewCount: 17,
      badge: '',
      badgeClass: '',
    },
    {
      title: 'C-500 Antioxidant Protect Dietary Supplement',
      store: 'Lucky Supermarket',
      image: 'assets/images/thumbs/product-img14.png',
      price: '$14.99',
      originalPrice: '$28.99',
      unit: '/Qty',
      rating: 4.8,
      reviewCount: 17,
      badge: 'Sale 50%',
      badgeClass: 'bg-danger-600 px-8 py-4 text-sm text-white',
    },
    {
      title: 'C-500 Antioxidant Protect Dietary Supplement',
      store: 'Lucky Supermarket',
      image: 'assets/images/thumbs/product-img15.png',
      price: '$14.99',
      originalPrice: '$28.99',
      unit: '/Qty',
      rating: 4.8,
      reviewCount: 17,
      badge: 'New',
      badgeClass: 'bg-warning-600 px-8 py-4 text-sm text-white',
    },
    {
      title: 'Good & Gather Farmed Atlantic Salmon',
      store: 'Lucky Supermarket',
      image: 'assets/images/thumbs/product-img16.png',
      price: '$14.99',
      originalPrice: '$28.99',
      rating: 4.8,
      badge: 'Sale 50%',
      badgeClass: 'bg-danger-600',
      reviewCount: 17,
    },
    {
      title: 'Market Pantry 41/50 Raw Tail-Off Large Raw Shrimp',
      store: 'Lucky Supermarket',
      image: 'assets/images/thumbs/product-img17.png',
      price: '$14.99',
      originalPrice: '$28.99',
      rating: 4.8,
      reviewCount: 17,
      badge: 'Sale 50%',
      badgeClass: 'bg-danger-600',
    },
    {
      title: 'Tropicana 100% Juice, Orange, No Pulp',
      store: 'Lucky Supermarket',
      image: 'assets/images/thumbs/product-img18.png',
      price: '$14.99',
      originalPrice: '$28.99',
      unit: '/Qty',
      rating: 4.8,
      reviewCount: 17,
      badge: 'New',
      badgeClass: 'bg-warning-600 px-8 py-4 text-sm text-white',
    },
  ];
  module.exports = recomandedProducts;
